package com.jetpackduba.gitnuro.di.modules

import com.jetpackduba.gitnuro.data.git.FileChangesWatcher
import com.jetpackduba.gitnuro.data.git.author.LoadAuthorGitAction
import com.jetpackduba.gitnuro.data.git.author.SaveAuthorGitAction
import com.jetpackduba.gitnuro.data.git.branches.CheckoutRefGitAction
import com.jetpackduba.gitnuro.data.git.branches.CreateBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.DeleteBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.DeleteLocallyRemoteBranchesGitAction
import com.jetpackduba.gitnuro.data.git.branches.GetBranchesGitAction
import com.jetpackduba.gitnuro.data.git.branches.GetCurrentBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.GetRemoteBranchesGitAction
import com.jetpackduba.gitnuro.data.git.branches.GetTrackingBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.MergeBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.RenameBranchGitAction
import com.jetpackduba.gitnuro.data.git.branches.SetTrackingBranchGitAction
import com.jetpackduba.gitnuro.data.git.config.LoadSignOffConfigGitAction
import com.jetpackduba.gitnuro.data.git.config.SaveLocalRepositoryConfigGitAction
import com.jetpackduba.gitnuro.data.git.diff.CanGenerateTextDiffGitAction
import com.jetpackduba.gitnuro.data.git.diff.FormatDiffGitAction
import com.jetpackduba.gitnuro.data.git.diff.FormatHunksGitAction
import com.jetpackduba.gitnuro.data.git.diff.GenerateSplitHunkFromDiffResultGitAction
import com.jetpackduba.gitnuro.data.git.diff.GetCommitDiffEntriesGitAction
import com.jetpackduba.gitnuro.data.git.diff.GetDiffContentGitAction
import com.jetpackduba.gitnuro.data.git.diff.GetDiffEntryFromStatusEntryGitAction
import com.jetpackduba.gitnuro.data.git.diff.TextDiffFromDiffLinesGitAction
import com.jetpackduba.gitnuro.data.git.lfs.AuthenticateLfsServerWithSshGitAction
import com.jetpackduba.gitnuro.data.git.lfs.DownloadLfsObjectGitAction
import com.jetpackduba.gitnuro.data.git.lfs.GetLfsObjectsGitAction
import com.jetpackduba.gitnuro.data.git.lfs.ProvideLfsCredentialsGitAction
import com.jetpackduba.gitnuro.data.git.lfs.UploadLfsObjectGitAction
import com.jetpackduba.gitnuro.data.git.lfs.VerifyUploadLfsObjectGitAction
import com.jetpackduba.gitnuro.data.git.log.CheckHasPreviousCommitsGitAction
import com.jetpackduba.gitnuro.data.git.log.CheckoutCommitGitAction
import com.jetpackduba.gitnuro.data.git.log.CherryPickCommitGitAction
import com.jetpackduba.gitnuro.data.git.log.FindCommitGitAction
import com.jetpackduba.gitnuro.data.git.log.GetLastCommitMessageGitAction
import com.jetpackduba.gitnuro.data.git.log.ResetToCommitGitAction
import com.jetpackduba.gitnuro.data.git.rebase.AbortRebaseGitAction
import com.jetpackduba.gitnuro.data.git.rebase.ContinueRebaseGitAction
import com.jetpackduba.gitnuro.data.git.rebase.GetCommitFromRebaseLineGitAction
import com.jetpackduba.gitnuro.data.git.rebase.GetRebaseAmendCommitIdGitAction
import com.jetpackduba.gitnuro.data.git.rebase.GetRebaseInteractiveStateGitAction
import com.jetpackduba.gitnuro.data.git.rebase.GetRebaseInteractiveTodoLinesGitAction
import com.jetpackduba.gitnuro.data.git.rebase.GetRebaseLinesFullMessageGitAction
import com.jetpackduba.gitnuro.data.git.rebase.RebaseBranchGitAction
import com.jetpackduba.gitnuro.data.git.rebase.ResumeRebaseInteractiveGitAction
import com.jetpackduba.gitnuro.data.git.rebase.SkipRebaseGitAction
import com.jetpackduba.gitnuro.data.git.rebase.StartRebaseInteractiveGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.CloneRepositoryGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.DeleteRemoteBranchGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.FetchAllRemotesGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.HandleTransportGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.HasPullResultConflictsGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.PullBranchGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.PullFromSpecificBranchGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.PushBranchGitAction
import com.jetpackduba.gitnuro.data.git.remote_operations.PushToSpecificBranchGitAction
import com.jetpackduba.gitnuro.data.git.remotes.AddRemoteGitAction
import com.jetpackduba.gitnuro.data.git.remotes.DeleteRemoteGitAction
import com.jetpackduba.gitnuro.data.git.remotes.GetRemotesGitAction
import com.jetpackduba.gitnuro.data.git.remotes.UpdateRemoteGitAction
import com.jetpackduba.gitnuro.data.git.repository.GetRepositoryStateGitAction
import com.jetpackduba.gitnuro.data.git.repository.InitLocalRepositoryGitAction
import com.jetpackduba.gitnuro.data.git.repository.OpenRepositoryGitAction
import com.jetpackduba.gitnuro.data.git.repository.OpenSubmoduleRepositoryGitAction
import com.jetpackduba.gitnuro.data.git.repository.ResetRepositoryStateGitAction
import com.jetpackduba.gitnuro.data.git.stash.ApplyStashGitAction
import com.jetpackduba.gitnuro.data.git.stash.DeleteStashGitAction
import com.jetpackduba.gitnuro.data.git.stash.GetStashListGitAction
import com.jetpackduba.gitnuro.data.git.stash.PopLastStashGitAction
import com.jetpackduba.gitnuro.data.git.stash.PopStashGitAction
import com.jetpackduba.gitnuro.data.git.submodules.AddSubmoduleGitAction
import com.jetpackduba.gitnuro.data.git.submodules.InitializeAllSubmodulesGitAction
import com.jetpackduba.gitnuro.data.git.submodules.InitializeSubmoduleGitAction
import com.jetpackduba.gitnuro.data.git.submodules.SyncSubmoduleGitAction
import com.jetpackduba.gitnuro.data.git.submodules.UpdateSubmoduleGitAction
import com.jetpackduba.gitnuro.data.git.tags.CreateTagGitAction
import com.jetpackduba.gitnuro.data.git.tags.DeleteTagGitAction
import com.jetpackduba.gitnuro.data.git.tags.GetTagsGitAction
import com.jetpackduba.gitnuro.data.git.workspace.CheckHasUncommittedChangesGitAction
import com.jetpackduba.gitnuro.data.git.workspace.DiscardEntriesGitAction
import com.jetpackduba.gitnuro.data.git.workspace.DiscardUnstagedHunkLineGitAction
import com.jetpackduba.gitnuro.data.git.workspace.DoCommitGitAction
import com.jetpackduba.gitnuro.data.git.workspace.GetIgnoreRulesGitAction
import com.jetpackduba.gitnuro.data.git.workspace.GetLinesFromRawTextGitAction
import com.jetpackduba.gitnuro.data.git.workspace.GetLinesFromTextGitAction
import com.jetpackduba.gitnuro.data.git.workspace.GetStatusGitAction
import com.jetpackduba.gitnuro.data.git.workspace.GetStatusSummaryGitAction
import com.jetpackduba.gitnuro.data.git.workspace.ResetHunkGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageAllGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageByDirectoryGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageEntryGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageHunkGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageHunkLineGitAction
import com.jetpackduba.gitnuro.data.git.workspace.StageUntrackedFileGitAction
import com.jetpackduba.gitnuro.data.git.workspace.UnstageAllGitAction
import com.jetpackduba.gitnuro.data.git.workspace.UnstageByDirectoryGitAction
import com.jetpackduba.gitnuro.data.git.workspace.UnstageEntryGitAction
import com.jetpackduba.gitnuro.data.git.workspace.UnstageHunkGitAction
import com.jetpackduba.gitnuro.data.git.workspace.UnstageHunkLineGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IAbortRebaseGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IAddRemoteGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IAddSubmoduleGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IApplyStashGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IAuthenticateLfsServerWithSshGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICanGenerateTextDiffGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICheckHasPreviousCommitsGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICheckHasUncommittedChangesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICheckoutCommitGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICheckoutRefGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICherryPickCommitGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICloneRepositoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IContinueRebaseGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICreateBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ICreateTagGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteLocallyRemoteBranchesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteRemoteBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteRemoteGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteStashGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDeleteTagGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDiscardEntriesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDiscardUnstagedHunkLineGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDoCommitGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IDownloadLfsObjectGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IFetchAllRemotesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IFileChangesWatcher
import com.jetpackduba.gitnuro.domain.interfaces.IFindCommitGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IFormatDiffGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IFormatHunksGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGenerateSplitHunkFromDiffResultGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetBranchesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetCommitDiffEntriesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetCommitFromRebaseLineGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetCurrentBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetDiffContentGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetDiffEntryFromStatusEntryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetIgnoreRulesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetLastCommitMessageGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetLfsObjectsGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetLinesFromRawTextGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetLinesFromTextGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRebaseAmendCommitIdGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRebaseInteractiveStateGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRebaseInteractiveTodoLinesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRebaseLinesFullMessageGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRemoteBranchesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRemotesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetRepositoryStateGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetStashListGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetStatusGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetStatusSummaryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetTagsGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IGetTrackingBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IHandleTransportGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IHasPullResultConflictsGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IInitLocalRepositoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IInitializeAllSubmodulesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IInitializeSubmoduleGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ILoadAuthorGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ILoadSignOffConfigGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IMergeBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IOpenRepositoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IOpenSubmoduleRepositoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPopLastStashGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPopStashGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IProvideLfsCredentialsGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPullBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPullFromSpecificBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPushBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IPushToSpecificBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IRebaseBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IRenameBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IResetHunkGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IResetRepositoryStateGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IResetToCommitGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IResumeRebaseInteractiveGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ISaveAuthorGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ISaveLocalRepositoryConfigGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ISetTrackingBranchGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ISkipRebaseGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageAllGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageByDirectoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageEntryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageHunkGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageHunkLineGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStageUntrackedFileGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IStartRebaseInteractiveGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ISyncSubmoduleGitAction
import com.jetpackduba.gitnuro.domain.interfaces.ITextDiffFromDiffLinesGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUnstageAllGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUnstageByDirectoryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUnstageEntryGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUnstageHunkGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUnstageHunkLineGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUpdateRemoteGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUpdateSubmoduleGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IUploadLfsObjectGitAction
import com.jetpackduba.gitnuro.domain.interfaces.IVerifyUploadLfsObjectGitAction
import dagger.Binds
import dagger.Module

@Module
interface FileWatcherModule {
    @Binds
    fun bindFileWatcher(watcher: FileChangesWatcher) : IFileChangesWatcher
}