package com.jetpackduba.gitnuro.ui.diff.syntax_highlighter

class CppSyntaxHighlighter : SyntaxHighlighter() {
    override fun loadKeywords(): List<String> = listOf(
        "asm",
        "double",
        "new",
        "switch",
        "auto",
        "else",
        "operator",
        "template",
        "break",
        "enum",
        "private",
        "this",
        "case",
        "extern",
        "protected",
        "throw",
        "catch",
        "float",
        "public",
        "try",
        "char",
        "for",
        "register",
        "typedef",
        "class",
        "friend",
        "return",
        "union",
        "const",
        "#include",
        "#define",
        "#ifndef",
        "#endif",
        "goto",
        "short",
        "unsigned",
        "continue",
        "if",
        "signed",
        "virtual",
        "default",
        "inline",
        "sizeof",
        "void",
        "delete",
        "int",
        "static",
        "volatile",
        "do",
        "long",
        "struct",
        "while",
    )

    override fun isAnnotation(word: String): Boolean = false
    override fun isComment(line: String): Boolean = line.startsWith("//")
}