package com.jetpackduba.gitnuro.ui.diff.syntax_highlighter

class ObjectiveCSyntaxHighlighter : SyntaxHighlighter() {
    override fun loadKeywords(): List<String> = listOf(
        "auto",
        "else",
        "long",
        "switch",
        "break",
        "enum",
        "register",
        "typedef",
        "case",
        "extern",
        "return",
        "union",
        "char",
        "float",
        "short",
        "unsigned",
        "const",
        "for",
        "signed",
        "void",
        "continue",
        "goto",
        "sizeof",
        "volatile",
        "default",
        "if",
        "static",
        "while",
        "do",
        "int",
        "struct",
        "_Packed",
        "double",
        "protocol",
        "interface",
        "@interface",
        "implementation",
        "@implementation",
        "NSObject",
        "NSInteger",
        "NSNumber",
        "CGFloat",
        "property",
        "nonatomic",
        "retain",
        "strong",
        "weak",
        "unsafe_unretained",
        "readwrite",
        "readonly",
    )

    override fun isAnnotation(word: String): Boolean = false
    override fun isComment(line: String): Boolean = line.startsWith("//")
}