package com.jetpackduba.gitnuro.domain.models

sealed interface TaskType {
    data object Unspecified : TaskType
    data object StageAllFiles : TaskType
    data object UnstageAllFiles : TaskType
    data object StageFile : TaskType
    data object UnstageFile : TaskType
    data object StageHunk : TaskType
    data object UnstageHunk : TaskType
    data object StageLine : TaskType
    data object UnstageLine : TaskType
    data object StageDir : TaskType
    data object UnstageDir : TaskType
    data object DiscardFile : TaskType
    data object DeleteFile : TaskType
    data object BlameFile : TaskType
    data object HistoryFile : TaskType
    data object DoCommit : TaskType
    data object AmendCommit : TaskType
    data object RevertCommit : TaskType
    data object CherryPickCommit : TaskType
    data object CheckoutCommit : TaskType
    data object ResetToCommit : TaskType
    data object CheckoutBranch : TaskType
    data object CheckoutRemoteBranch : TaskType
    data object CreateBranch : TaskType
    data object DeleteBranch : TaskType
    data object RenameBranch : TaskType
    data object MergeBranch : TaskType
    data object RebaseBranch : TaskType
    data object RebaseInteractive : TaskType
    data object ContinueRebase : TaskType
    data object AbortRebase : TaskType
    data object SkipRebase : TaskType
    data object ChangeBranchUpstream : TaskType
    data object PullFromBranch : TaskType
    data object PushToBranch : TaskType
    data object DeleteRemoteBranch : TaskType
    data object Pull : TaskType
    data object Push : TaskType
    data object Fetch : TaskType
    data object Stash : TaskType
    data object ApplyStash : TaskType
    data object PopStash : TaskType
    data object DeleteStash : TaskType
    data object CreateTag : TaskType
    data object CheckoutTag : TaskType
    data object DeleteTag : TaskType
    data object AddSubmodule : TaskType
    data object DeleteSubmodule : TaskType
    data object InitSubmodule : TaskType
    data object DeinitSubmodule : TaskType
    data object SyncSubmodule : TaskType
    data object UpdateSubmodule : TaskType
    data object SaveCustomTheme : TaskType
    data object ResetRepoState : TaskType
    data object ChangesDetection : TaskType
    data object RepositoryOpen : TaskType
    data object RepositoryClone : TaskType
    data object AddRemote : TaskType
    data object DeleteRemote : TaskType
    data object LoadAuthor : TaskType
}